image: maven:3.6.1-jdk-8

variables:
    MAVEN_CLI_OPTS: "--show-version"
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Djava.awt.headless=true"

cache:
    key: $CI_PIPELINE_IID
    policy: pull
    paths:
    - $CI_PROJECT_DIR/.m2/repository # cache maven repository across all jobs

include:
    - template: Code-Quality.gitlab-ci.yml
  
 
stages:
    - build
    - test
    - package
    - deploy

##############
### BUILD

.build:
    stage: build
    cache:
        key: $CI_PIPELINE_IID
        policy: push # this is the only job that needs to publish to the cache, therefore it is overriding the policy
        paths:
            - $CI_PROJECT_DIR/.m2/repository

platform-core-build:
    extends: .build
    script:
        - mvn $MAVEN_CLI_OPTS clean compile install -f system/platform-core

rest-core-build:
    extends: .build
    script:
        - mvn $MAVEN_CLI_OPTS clean compile install -f system/rest-spring

hazlecast-connector-build:
    extends: .build
    script:
        - mvn $MAVEN_CLI_OPTS clean compile install -f connectors/hazelcast/hazelcast-connector

kafka-connector-build:
    extends: .build
    script:
        - mvn $MAVEN_CLI_OPTS clean compile install -f connectors/kafka/kafka-connector

api-playground-build:
    extends: .build
    script:
        - mvn $MAVEN_CLI_OPTS clean compile install -f connectors/extensions/api-playground

distributed=tracer-build:
    extends: .build
    script:
        - mvn $MAVEN_CLI_OPTS clean compile install -f connectors/extensions/distributed-tracer

rest-automation-app-build:
    extends: .build
    script:
        - mvn $MAVEN_CLI_OPTS clean compile install -f connectors/extensions/rest-automation-app

rest-automation-lib-build:
    extends: .build
    script:
        - mvn $MAVEN_CLI_OPTS clean compile install -f connectors/extensions/rest-automation-lib-build

websocket-notification-build:
    extends: .build
    script:
        - mvn $MAVEN_CLI_OPTS clean compile install -f connectors/extensions/websocket-notification

##############
### TEST

test_and_coverage:
    stage: test
    script:
        - mvn $MAVEN_CLI_OPTS test -f system/platform-core
        - ls -la system/platform-core/target/surefire-reports
        - cat system/platform-core/target/site/jacoco/index.html
        - mv system/platform-core/target/site/jacoco jacoco
    coverage: '/Total.*?([0-9]{1,3})%/'
    artifacts:
        reports:
            junit:
                - system/platform-core/target/surefire-reports/TEST-*.xml
        paths:
            - jacoco
        expire_in: 30 days

 
javadoc: 
    stage: package
    script: 
        - mvn $MAVEN_CLI_OPTS javadoc:javadoc -f system/platform-core
        - mv system/platform-core/target/site/apidocs apidocs
    artifacts:
        paths:
            - apidocs
        expire_in: 30 days
        
pages:
    stage: deploy
    dependencies:
        - test_and_coverage
        - javadoc
    script:
        - mkdir -p public/coverage public/docs
        - mv jacoco/* public/coverage
        - mv apidocs/* public/docs
    artifacts:
        paths:
        - public
        expire_in: 90 days
 
